# Split package recipe for krb5
# - libkrb5: Kerberos libraries and headers for development
# - krb5: Kerberos utilities and executables
{% set name = "krb5" %}
{% set version = "1.21.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/krb5/{{ name }}/archive/{{ name }}-{{ version }}-final.tar.gz
  sha256: 2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - bison       # [not win]
    - autoconf    # [not win]
    - posix       # [win]
    - perl        # [win]
    - pkg-config  # [unix]
    - make        # [unix]
    - python *    # [not win]
    - gettext     # [not win]
  host:
    - libedit {{ libedit}}  # [unix]
    - openssl {{ openssl }}

outputs:
  - name: lib{{ name }}
    script: build-libkrb5.sh   # [unix]
    script: build-libkrb5.bat  # [win]
    files:
      # Libraries (krb5 specific only, exclude ncurses/libedit components)
      - lib/libkrb5*.so*           # [linux]
      - lib/libgssapi*.so*         # [linux]
      - lib/libgssrpc*.so*         # [linux]
      - lib/libkadm5*.so*          # [linux]
      - lib/libkdb5*.so*           # [linux]
      - lib/libkrad*.so*           # [linux]
      - lib/libk5crypto*.so*       # [linux]
      - lib/libcom_err*.so*        # [linux]
      - lib/libverto*.so*          # [linux]
      - lib/libcrypto*.so*         # [linux]
      - lib/libssl*.so*            # [linux]
      - lib/libkrb5*.dylib        # [osx]
      - lib/libgssapi*.dylib      # [osx]
      - lib/libgssrpc*.dylib      # [osx]
      - lib/libkadm5*.dylib       # [osx]
      - lib/libkdb5*.dylib        # [osx]
      - lib/libkrad*.dylib        # [osx]
      - lib/libk5crypto*.dylib    # [osx]
      - lib/libcom_err*.dylib     # [osx]
      - lib/libverto*.dylib       # [osx]
      - lib/libcrypto*.dylib      # [osx]
      - lib/libssl*.dylib         # [osx]
      - lib/*.dll                 # [win]
      # Headers  
      - include/**/*
      # Development tools only
      - bin/krb5-config        # [unix]
      - bin/compile_et         # [unix]
      # Package config files
      - lib/pkgconfig/*.pc
      # Plugin architecture
      - lib/krb5/plugins/**/*
      # Development support files
      - share/et/**/*
      - share/man/man1/krb5-config.1  # [unix]
      - share/man/man1/compile_et.1   # [unix]
    build:
      run_exports:
        - {{ pin_subpackage('libkrb5', max_pin='x.x') }}
      ignore_run_exports:
        # C++ is only needed for performing built-in unit tests.
        - libcxx          # [osx]
        - libstdcxx-ng    # [linux]
        # libedit is not used in the libraries, only in some utilities
        - libedit         # [unix]
        # ncurses and all its components pulled in by libedit but not needed for krb5 libraries  
        - ncurses         # [unix]
      missing_dso_whitelist:          # [osx]
        - /usr/lib/libresolv.9.dylib  # [osx]
    requirements:
      build:
        - libtool  # [unix]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - bison       # [not win]
        - autoconf    # [not win]
        - posix       # [win]
        - perl        # [win]
        - pkg-config  # [unix]
        - make        # [unix]
        - python *    # [not win]
        - gettext
      host:
        - libedit {{ libedit}}  # [unix]
        - openssl {{ openssl }}
      run:
    test:
      commands:
        - test -f $PREFIX/lib/libkrb5.so                    # [linux]
        - test -f $PREFIX/lib/libkrb5.dylib                 # [osx]
        - test -f $PREFIX/lib/libgssapi_krb5.so             # [linux]
        - test -f $PREFIX/lib/libgssapi_krb5.dylib          # [osx]
        - krb5-config --version
        - test -f $PREFIX/bin/krb5-config                   # [unix]
        - test ! -f $PREFIX/bin/kinit                       # [unix]
        - test ! -f $PREFIX/bin/klist                       # [unix]

  - name: {{ name }}
    script: build-krb5.sh   # [unix]
    script: build-krb5.bat  # [win]
    files:
      # User utilities
      - bin/kinit              # [unix]
      - bin/klist              # [unix] 
      - bin/kdestroy           # [unix]
      - bin/kpasswd            # [unix]
      - bin/kswitch            # [unix]
      - bin/ktutil             # [unix]
      - bin/kvno               # [unix]
      - bin/k5srvutil          # [unix]
      - bin/kadmin             # [unix]
      - bin/gss-client         # [unix]
      - bin/sclient            # [unix]
      - bin/sim_client         # [unix]
      - bin/uuclient           # [unix]
      # Server utilities
      - sbin/kadmin.local      # [unix]
      - sbin/kadmind           # [unix]
      - sbin/kdb5_util         # [unix]
      - sbin/kprop             # [unix]
      - sbin/kpropd            # [unix]
      - sbin/kproplog          # [unix]
      - sbin/krb5kdc           # [unix]
      - sbin/krb5-send-pr      # [unix]
      - sbin/gss-server        # [unix]
      - sbin/sim_server        # [unix]
      - sbin/sserver           # [unix]
      - sbin/uuserver          # [unix]
      # Manual pages for utilities
      - share/man/man1/kinit.1         # [unix]
      - share/man/man1/klist.1         # [unix]
      - share/man/man1/kdestroy.1      # [unix]
      - share/man/man1/kpasswd.1       # [unix]
      - share/man/man1/kswitch.1       # [unix]
      - share/man/man1/ktutil.1        # [unix]
      - share/man/man1/kvno.1          # [unix]
      - share/man/man1/k5srvutil.1     # [unix]
      - share/man/man1/kadmin.1        # [unix]
      - share/man/man1/sclient.1       # [unix]
      - share/man/man8/kadmin.local.8  # [unix]
      - share/man/man8/kadmind.8       # [unix]
      - share/man/man8/kdb5_util.8     # [unix]
      - share/man/man8/kprop.8         # [unix]
      - share/man/man8/kpropd.8        # [unix]
      - share/man/man8/kproplog.8      # [unix]
      - share/man/man8/krb5kdc.8       # [unix]
      - share/man/man8/sserver.8       # [unix]
    requirements:
      run:
        - {{ pin_subpackage('libkrb5', exact=True) }}
        - libedit  # [unix]
    test:
      commands:
        - kinit 2>&1 | grep -q "Usage:" || true       # [unix]
        - klist 2>&1 | grep -q "Usage:" || true       # [unix]  
        - test -f $PREFIX/bin/kdestroy                 # [unix]
        - test -f $PREFIX/bin/kinit                    # [unix]
        - test -f $PREFIX/bin/klist                    # [unix]
        - test ! -f $PREFIX/bin/krb5-config            # [unix]

about:
  home: https://web.mit.edu/kerberos/
  license: MIT
  license_family: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
  description: |
    Kerberos is a network authentication protocol. It is designed to provide strong authentication for client/server applications by using secret-key cryptography. 
  doc_url: https://web.mit.edu/kerberos/krb5-1.21/doc/index.html
  dev_url: https://github.com/krb5/krb5

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - mingwandroid
    - mariusvniekerk
    - chenghlee
