{% set name = "krb5" %}
{% set version = "1.21.3" %}

# Platform-specific prefixes and suffixes
{% set unix_prefix = "" %}  # [not win]
{% set unix_suffix = "" %}  # [not win]
{% set win_prefix = "Library/" %}  # [win]
{% set win_suffix = ".exe" %}  # [win]

# Define library names for cleaner templating
{% set krb5_libs = ["krb5", "gssapi", "gssrpc", "kadm5", "kdb5", "krad", "k5crypto", "com_err", "verto"] %}
{% set krb5_headers = ["krb5", "gssapi", "kadm5", "kdb5", "krad", "k5crypto"] %}
{% set unix_prefix = "" %}  # [not win]
{% set unix_suffix = "" %}  # [not win]
{% set win_prefix = "Library/" %}  # [win]
{% set win_suffix = ".exe" %}  # [win]

# Define library names for cleaner templating
{% set krb5_libs = ["krb5", "gssapi", "gssrpc", "kadm5", "kdb5", "krad", "k5crypto", "com_err", "verto"] %}
{% set krb5_headers = ["krb5", "gssapi", "kadm5", "kdb5", "krad", "k5crypto"] %}
{% set krb5_executables = ["kinit", "klist", "kdestroy", "kpasswd", "kswitch", "ktutil", "kvno", "k5srvutil", "kadmin", "gss-client", "sclient", "sim_client", "uuclient", "ksu", "krb5-config"] %}
{% set krb5_server_executables = ["kadmin.local", "kadmind", "kdb5_util", "kprop", "kpropd", "kproplog", "krb5kdc", "krb5-send-pr", "gss-server", "sim_server", "sserver", "uuserver"] %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/krb5/{{ name }}/archive/{{ name }}-{{ version }}-final.tar.gz
  sha256: 2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861

build:
  number: 3
  skip: true  # [win and vc<14]
  missing_dso_whitelist:
    - api-ms-win-core-winrt-string-l1-1-0.dll  # [win]
    - api-ms-win-core-winrt-error-l1-1-0.dll   # [win]
    - api-ms-win-core-winrt-l1-1-0.dll         # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - libtool  # [unix]
    - bison       # [not win]
    - autoconf    # [not win]
    - posix       # [win]
    - perl        # [win]
    - pkg-config  # [unix]
    - make        # [unix]
    - python *    # [not win]
    - gettext     # [not win]
  host:
    - libedit  # [unix]
    - openssl
    - lmdb                  # [unix]

outputs:
  - name: lib{{ name }}
    script: build.sh   # [unix]
    script: bld.bat    # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libkrb5', max_pin='x.x') }}
      ignore_run_exports:
        - libcxx          # [osx]
        - libstdcxx-ng    # [linux]
        - libedit         # [unix]
        - ncurses         # [unix]
    files:
      # Libraries - Unix
      {% for lib in krb5_libs %}
      - lib/lib{{ lib }}*      # [unix]
      {% endfor %}
      # Libraries - Windows
      - {{ win_prefix }}lib/*.lib # [win]
      {% for lib in krb5_libs %}
      - {{ win_prefix }}bin/{{ lib }}*.dll # [win]
      {% endfor %}
      
      # Headers - Unix
      {% for header in krb5_headers %}
      - include/{{ header }}/     # [unix]
      {% endfor %}
      - include/com_err.h # [unix]
      - include/verto.h   # [unix]
      - include/krb5.h    # [unix]
      - include/gssapi.h  # [unix]
      - include/gssapi_krb5.h # [unix]
      - include/gssrpc.h  # [unix]
      - include/kadm5.h   # [unix]
      - include/kdb5.h    # [unix]
      - include/krad.h    # [unix]
      - include/k5crypto.h # [unix]
      
      # Headers - Windows
      {% for header in krb5_headers %}
      - {{ win_prefix }}include/{{ header }}/ # [win]
      {% endfor %}
      - {{ win_prefix }}include/com_err.h # [win]
      - {{ win_prefix }}include/verto.h # [win]
      - {{ win_prefix }}include/krb5.h # [win]
      - {{ win_prefix }}include/gssapi.h # [win]
      - {{ win_prefix }}include/gssapi_krb5.h # [win]
      - {{ win_prefix }}include/gssrpc.h # [win]
      - {{ win_prefix }}include/kadm5.h # [win]
      - {{ win_prefix }}include/kdb5.h # [win]
      - {{ win_prefix }}include/krad.h # [win]
      - {{ win_prefix }}include/k5crypto.h # [win]
      - {{ win_prefix }}include/verto.h # [win]
      
      # Development tools (only compile_et, krb5-config goes to krb5 package)
      - bin/compile_et    # [unix]
      
      # Package config
      - lib/pkgconfig/*.pc # [unix]
      
      # Plugins
      - lib/krb5/plugins/**/* # [unix]
      - {{ win_prefix }}bin/plugins/**/* # [win]
      
      # Documentation
      - share/et/**/*     # [unix]
      - share/examples/**/* # [unix]
      - share/locale/**/* # [unix]
      - share/man/man1/compile_et.1  # [unix]
      - share/man/man5/**/* # [unix]
      - share/man/man7/**/* # [unix]
      
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - libtool  # [unix]
        - bison       # [not win]
        - autoconf    # [not win]
        - posix       # [win]
        - perl        # [win]
        - pkg-config  # [unix]
        - make        # [unix]
        - python *    # [not win]
        - gettext     # [not win]
      host:
        - libedit  # [unix]
        - openssl
        - lmdb                  # [unix]
      run:
        - lmdb                  # [unix]
    test:
      commands:
        - test -f $PREFIX/lib/libkrb5${SHLIB_EXT} # [unix]
        - test -f $PREFIX/include/krb5.h          # [unix]
        - test -f $PREFIX/Library/bin/krb5_64.dll # [win]
        - test -f $PREFIX/Library/include/krb5.h  # [win]

  - name: {{ name }}
    script: build.sh   # [unix]
    script: bld.bat    # [win]
    script: move-files.py
    build:
      ignore_run_exports:
        - openssl
    files:
      # Files moved to staging by move-files.py
      - staging/bin/
      - staging/sbin/
      - staging/share/man/
      # Windows executables
      - {{ win_prefix }}bin/*{{ win_suffix }}      # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - libtool  # [unix]
        - bison       # [not win]
        - autoconf    # [not win]
        - posix       # [win]
        - perl        # [win]
        - pkg-config  # [unix]
        - make        # [unix]
        - python *    # [not win]
        - gettext     # [not win]
      host:
        - libedit  # [unix]
        - openssl
        - lmdb                  # [unix]
        - {{ pin_subpackage('libkrb5', exact=True) }}
      run:
        - {{ pin_subpackage('libkrb5', exact=True) }}
        - libedit  # [unix]
        - openldap # [linux]
        - lmdb     # [unix]
    test:
      commands:
        # Test for key executables in staging
        - test -f $PREFIX/staging/bin/kinit
        - test -f $PREFIX/staging/bin/klist
        - test -f $PREFIX/staging/bin/kdestroy
        - test -f $PREFIX/staging/bin/krb5-config
        - test -f $PREFIX/staging/sbin/krb5kdc
        # Test for Windows executables
        - test -f $PREFIX/Library/bin/kinit.exe # [win]
        - test -f $PREFIX/Library/bin/klist.exe # [win]
        # Verify files are not in wrong locations
        - test ! -f $PREFIX/bin/krb5-config
        - test ! -f $PREFIX/lib/libkrb5${SHLIB_EXT}

about:
  home: https://web.mit.edu/kerberos/
  license: MIT
  license_family: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
  description: |
    Kerberos is a network authentication protocol. It is designed to provide strong authentication for client/server applications by using secret-key cryptography. 
  doc_url: https://web.mit.edu/kerberos/krb5-1.21/doc/index.html
  dev_url: https://github.com/krb5/krb5

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - mingwandroid
    - mariusvniekerk
    - chenghlee
