{% set version = "1.14.6" %}

package:
  name: krb5
  version: {{ version }}

source:
  fn: krb5-{{ version }}.tar.gz
  url: https://github.com/krb5/krb5/archive/krb5-{{ version }}-final.tar.gz
  sha256: 34c7d6dfdd03d3c6827676a4c8e8fc590727ce396487da8d1b761ad39d728d9a
  patches:
    - eafnosupport.patch  # [win and py<34]
    - jsoneoverflow.patch  # [win and py<34]
    - afxres.patch  # [win and py<35]
    - lshutil.patch  # [win and py<35]
    - noleash.patch  # [win]
    - noinstallleash.patch  # [win]

build:
  number: 4
  features:
    - vc{{ vc }}  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison  # [not win]
    - autoconf  # [not win]
  host:
    - msinttypes  # [win and vc<14]
    - libedit  # [unix]
    - openssl
    - tk

test:
  requires:
    - {{ compiler('c') }}
  commands:
    - conda inspect linkages -p $PREFIX krb5  # [not win]
    - conda inspect objects -p $PREFIX krb5  # [osx]

about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: 'A network authentication protocol.'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - mingwandroid
