{% set version = "1.16" %}

package:
  name: krb5
  version: {{ version }}

source:
  url: https://github.com/krb5/krb5/archive/krb5-{{ version }}-final.tar.gz
  sha256: b416ba519317fcccac967c91cb995b0162d9b4c53de459a78330133fbeb4d01e
  patches:
    - eafnosupport.patch  # [win and py<34]
    - jsoneoverflow.patch  # [win and py<34]
    - afxres.patch  # [win and py<35]
    - lshutil.patch  # [win and py<35]
    # https://github.com/krb5/krb5/pull/721
    - 0002-Initialize-return-value-to-NULL-in-appdefault_get.patch

build:
  number: 6
  run_exports:
    # stable within minor revisions: https://abi-laboratory.pro/tracker/timeline/krb5/
    - {{ pin_subpackage('krb5', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison  # [not win]
    - autoconf  # [not win]
    - posix  # [win]
    - perl  5.20.*   # [win]
    - pkg-config  # [unix]
  host:
    - msinttypes  # [win and vc<14]
    - libedit  # [unix]
    - openssl
    - tk
  run:
    - {{ pin_compatible('libedit') }}  # [unix]

test:
  requires:
    - {{ compiler('c') }}
  commands:
    - conda inspect linkages -p $PREFIX krb5  # [not win]
    - conda inspect objects -p $PREFIX krb5  # [osx]

about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: 'A network authentication protocol.'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - mingwandroid
