{% set version = "1.14.2" %}

package:
  name: krb5
  version: {{ version }}

source:
  fn: krb5-{{ version }}.tar.gz
  url: https://github.com/krb5/krb5/archive/krb5-{{ version }}-final.tar.gz
  sha256: e8ee5336ee3e9f5a4a9696ab12010a7bb105641788edd95323aeab3e77825b1a
  patches:
    - eafnosupport.patch  # [win and py<34]
    - jsoneoverflow.patch  # [win and py<34]
    - afxres.patch  # [win and py<35]
    - lshutil.patch  # [win and py<35]
    - noleash.patch  # [win]
    - noinstallleash.patch  # [win]

build:
  number: 0
  skip: True  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - bison  # [not win]
    - autoconf  # [not win]
    - msinttypes  # [win and py<35]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - conda inspect linkages -p $PREFIX krb5  # [not win]
    - conda inspect objects -p $PREFIX krb5  # [osx]

about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: 'A network authentication protocol.'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
