{% set name = "krb5" %}
{% set version = "1.21.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/krb5/{{ name }}/archive/{{ name }}-{{ version }}-final.tar.gz
  sha256: 2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861

build:
  number: 3
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - libtool  # [unix]
    - bison       # [not win]
    - autoconf    # [not win]
    - posix       # [win]
    - perl        # [win]
    - pkg-config  # [unix]
    - make        # [unix]
    - python *    # [not win]
    - gettext     # [not win]
  host:
    - libedit {{ libedit}}  # [unix]
    - openssl {{ openssl }}
    - lmdb                  # [unix]

outputs:
  - name: lib{{ name }}
    script: build.sh   # [unix]
    script: build.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libkrb5', max_pin='x.x') }}
      ignore_run_exports:
        - libcxx          # [osx]
        - libstdcxx-ng    # [linux]
        - libedit         # [unix]
        - ncurses         # [unix]
    files:
      # Libraries
      - lib/libkrb5*      # [unix]
      - lib/libgssapi*    # [unix]
      - lib/libgssrpc*    # [unix]
      - lib/libkadm5*     # [unix]
      - lib/libkdb5*      # [unix]
      - lib/libkrad*      # [unix]
      - lib/libk5crypto*  # [unix]
      - lib/libcom_err*   # [unix]
      - lib/libverto*     # [unix]
      - Library/lib/*.lib # [win]
      - Library/bin/*.dll # [win]
      # Headers
      - include/**/*      # [unix]
      - Library/include/**/* # [win]
      # Development tools
      - bin/krb5-config   # [unix]
      - bin/compile_et    # [unix]
      # Package config
      - lib/pkgconfig/*.pc # [unix]
      # Plugins
      - lib/krb5/plugins/**/* # [unix]
      - Library/bin/plugins/**/* # [win]
      # Documentation
      - share/et/**/*     # [unix]
      - share/examples/**/* # [unix]
      - share/locale/**/* # [unix]
      - share/man/man1/krb5-config.1 # [unix]
      - share/man/man1/compile_et.1  # [unix]
      - share/man/man5/**/* # [unix]
      - share/man/man7/**/* # [unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - libtool  # [unix]
        - bison       # [not win]
        - autoconf    # [not win]
        - posix       # [win]
        - perl        # [win]
        - pkg-config  # [unix]
        - make        # [unix]
        - python *    # [not win]
        - gettext     # [not win]
      host:
        - libedit {{ libedit}}  # [unix]
        - openssl {{ openssl }}
        - lmdb                  # [unix]
      run:
        - lmdb                  # [unix]
    test:
      commands:
        - test -f $PREFIX/lib/libkrb5${SHLIB_EXT} # [unix]
        - test -f $PREFIX/include/krb5.h          # [unix]
        - krb5-config --version                   # [unix]
        - test -f $PREFIX/Library/bin/krb5_64.dll # [win]
        - test -f $PREFIX/Library/include/krb5.h  # [win]

  - name: {{ name }}
    script: build.sh   # [unix]
    script: build.bat  # [win]
    build:
      ignore_run_exports:
        - openssl
    files:
      # User utilities
      - bin/kinit
      - bin/klist
      - bin/kdestroy
      - bin/kpasswd
      - bin/kswitch
      - bin/ktutil
      - bin/kvno
      - bin/k5srvutil
      - bin/kadmin
      - bin/gss-client
      - bin/sclient
      - bin/sim_client
      - bin/uuclient
      - bin/ksu                # [linux]
      - Library/bin/*.exe      # [win]
      # Server utilities
      - sbin/kadmin.local
      - sbin/kadmind
      - sbin/kdb5_util
      - sbin/kprop
      - sbin/kpropd
      - sbin/kproplog
      - sbin/krb5kdc
      - sbin/krb5-send-pr
      - sbin/gss-server
      - sbin/sim_server
      - sbin/sserver
      - sbin/uuserver
      # Manual pages
      - share/man/man1/kinit.1
      - share/man/man1/klist.1
      - share/man/man1/kdestroy.1
      - share/man/man1/kpasswd.1
      - share/man/man1/kswitch.1
      - share/man/man1/ktutil.1
      - share/man/man1/kvno.1
      - share/man/man1/k5srvutil.1
      - share/man/man1/kadmin.1
      - share/man/man1/sclient.1
      - share/man/man1/ksu.1           # [linux]
      - share/man/man8/kadmin.local.8
      - share/man/man8/kadmind.8
      - share/man/man8/kdb5_util.8
      - share/man/man8/kprop.8
      - share/man/man8/kpropd.8
      - share/man/man8/kproplog.8
      - share/man/man8/krb5kdc.8
      - share/man/man8/sserver.8
      - share/man/man8/kdb5_ldap_util.8
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - libtool  # [unix]
        - bison       # [not win]
        - autoconf    # [not win]
        - posix       # [win]
        - perl        # [win]
        - pkg-config  # [unix]
        - make        # [unix]
        - python *    # [not win]
        - gettext     # [not win]
      host:
        - libedit {{ libedit}}  # [unix]
        - openssl {{ openssl }}
        - lmdb                  # [unix]
        - {{ pin_subpackage('libkrb5', exact=True) }}
      run:
        - {{ pin_subpackage('libkrb5', exact=True) }}
        - libedit  # [unix]
        - openldap # [linux]
        - lmdb     # [unix]
    test:
      commands:
        - test -f $PREFIX/bin/kinit
        - test -f $PREFIX/bin/klist
        - test -f $PREFIX/bin/kdestroy
        - test -f $PREFIX/sbin/krb5kdc
        - test -f $PREFIX/Library/bin/kinit.exe # [win]
        - test -f $PREFIX/Library/bin/klist.exe # [win]
        - test ! -f $PREFIX/bin/krb5-config
        - test ! -f $PREFIX/lib/libkrb5${SHLIB_EXT}

about:
  home: https://web.mit.edu/kerberos/
  license: MIT
  license_family: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
  description: |
    Kerberos is a network authentication protocol. It is designed to provide strong authentication for client/server applications by using secret-key cryptography. 
  doc_url: https://web.mit.edu/kerberos/krb5-1.21/doc/index.html
  dev_url: https://github.com/krb5/krb5

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - mingwandroid
    - mariusvniekerk
    - chenghlee
