travis:
  secure:
    BINSTAR_TOKEN: Jt/Co/lqkoRy3zrHsnpZOySUtsDniw/LE7i96uDT2mC4kQAWaAFiBpUMDOZUErQFwYA8BxsjCjABEz1QVFdTEaXdXbVeAX4CQKn2XWGC6f9Rlq72KeAcZPU4f911d8nDcl80/9XJ0DtUPnQ4ZKewMnJqbR5UQKVHulJtKtfs3MHMqBv9hAxXYWna0oscMul9LFgLDyW8VPnwwQnUiMVi3ehU8aC8eCSanTJfJYa5cstLwrWX+8wv7GRB1DKbngh9M3w7CAeDllsftIpEw0ABuv7wpsjAWgAgAgWku8tIRAKOpgrVThrLwhUmLEM3W9siJSDo+gxzHj17c9A+39KV6dFdgI0qSLHRyej00PmvyKvU2oswm6fqfMUqMwU48adV+lAYZ0o6+/kSOC0lrMVJZNE8/Myx7GM04t7hM3iTJJHvhc6xIsbqclevPvyV1Pn5E8yfv2+EwOhN2KxtBuzyHfZOjN37vG0NOn4XXFpyMHnxG4bA5TKTpvCPj7y260I6Je5/+mPoGfd6CwbnQBM+SFVe0axxbxlT/W13d7YDT87XrIXrptzY2Seb40ECueEEtU0EinPKBhj47fFWBclFerf7KWn4Gp/B2msDKXgmt33VfNdfL8IbqLRMg8g4y9T5SnHyTLU8nlkJvD+4tOHRM8Fnat4tB8dzfEUbJ//1oWo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
